version: "3.8"

services:
  qna:
    image: qna
    build: 
      context: .
      dockerfile: ./docker/qna.dockerfile
    ports: 
      - 8080:8080
  
  nginx:
    image: nginx
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 80:80